### ISSUE TITLE
There is no TC autoinstall archive in latest, Initial version 0.9-beta.2

### ISSUE THREAD

**Issue by amidarius** [WouterVanNifterick/wfx-s3-wvn#3]
Solution is to install plugin manually.
Not problem for me but, someone with lesser knowledge about this can't do that.

**Comment by WouterVanNifterick** [comment]
Thanks for reporting!.

Added a new release, and this time uploaded an installer zip :D 

https://github.com/WouterVanNifterick/wfx-s3-wvn/releases
